services:
  class_db:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - bookingApp

  class_service:
    build: ./class_service/
    container_name: class_service
    ports: ["5000:5000"]
    depends_on:
      - class_db
    networks:
      - bookingApp

  user_db:
    image: mongo:latest
    command: mongod --port 27018
    ports:
      - 27018-27018
    networks:
      - bookingApp

  user_service:
    build: ./user_service/
    container_name: user_service
    ports: ["5001:5001"]
    depends_on:
      - user_db
    networks:
      - bookingApp

  get_class_complex_service:
    build: ./get_class_complex_service/
    container_name: get_class_complex_service
    ports: ["5005:5005"]
    networks:
      - bookingApp

networks:
  bookingApp:
    driver: bridge
